# syntax=docker/dockerfile:1
FROM alpine:latest

RUN apk update
RUN apk add py-pip
RUN apk add --no-cache python3-dev

# copy over our requirements.txt file
COPY requirements.txt /tmp/

# upgrade pip
RUN pip install -U pip

# install required python packages & 
# dissable caching to keep image small
RUN pip install -r /tmp/requirements.txt

# copy over our app code
COPY ./app /app